### ISSUE TITLE
Use zock for mocking in unit tests

### ISSUE THREAD

**Issue by pahen** [aptoma/ass-client-js#2]
See https://github.com/claydotio/zock

Must wait for https://github.com/claydotio/zock/pull/7 to get merged first though.

**Comment by martinj** [comment]
Written in coffescript, will not get much traction in the long run >.< 
I guess there is not many other alternatives.

**Comment by pahen** [comment]
Yes, that sucks .. I tried https://github.com/algolia/faux-jax which supports both Browser and Node but the API sucks. I'll run nock and sinon for now until we find a better way.
